#mysql JPA
spring:
  jpa:
    hibernate:
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
      ddl-auto: create
      use-new-id-generator-mappings: 'true'
    properties:
      hibernate:
        format_sql: 'true'
        show_sql: 'true'
    database: mysql
    show-sql: 'true'

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      password: im509teller!
      username: classic
    url: jdbc:mysql://localhost:3306/imteller?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true

  # documentationPluginsBootstrapper 해결
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER